<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- keep the interpreter and AOT builds apart so they never share intermediate files -->
  <PropertyGroup Condition="'$(RunAOTCompilation)' == 'true'">
    <BaseIntermediateOutputPath>obj/aot/</BaseIntermediateOutputPath>
    <BaseOutputPath>bin/aot/</BaseOutputPath>
  </PropertyGroup>

</Project>
