<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(CanTargetNet11)' == 'true'">$(TargetFrameworks);net11.0</TargetFrameworks>
    <RootNamespace>Easy.Template.XCS.Test</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Easy.Template.XCS\Easy.Template.XCS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fixtures\Files\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\Res\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
